server.port=8182
spring.application.name=eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dirección en la que expone el servicio
eureka.client.service-url.defaultZone=http://localhost:8182/eureka/